// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCEdap-TJmyr72aljNRbHL1k8Qw_vbv8IE',
//     appId: '1:691454814723:web:0f02ecc562b2184b6cbc36',
//     messagingSenderId: '691454814723',
//     projectId: 'fruits-app-5e4e0',
//     authDomain: 'fruits-app-5e4e0.firebaseapp.com',
//     storageBucket: 'fruits-app-5e4e0.appspot.com',
//     measurementId: 'G-V3ZZGPDLQ0',
//   );
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCci4CxRC8feEgpvajxIuDw4A7RXWcH3BQ',
//     appId: '1:691454814723:android:5112362529729c606cbc36',
//     messagingSenderId: '691454814723',
//     projectId: 'fruits-app-5e4e0',
//     storageBucket: 'fruits-app-5e4e0.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCXQX_OFwX7H_sddZu7gZ6c1lsrphXfDm0',
//     appId: '1:691454814723:ios:48ca2eff3139179c6cbc36',
//     messagingSenderId: '691454814723',
//     projectId: 'fruits-app-5e4e0',
//     storageBucket: 'fruits-app-5e4e0.appspot.com',
//     iosBundleId: 'com.example.fruitsApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCXQX_OFwX7H_sddZu7gZ6c1lsrphXfDm0',
//     appId: '1:691454814723:ios:48ca2eff3139179c6cbc36',
//     messagingSenderId: '691454814723',
//     projectId: 'fruits-app-5e4e0',
//     storageBucket: 'fruits-app-5e4e0.appspot.com',
//     iosBundleId: 'com.example.fruitsApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCEdap-TJmyr72aljNRbHL1k8Qw_vbv8IE',
//     appId: '1:691454814723:web:3a2b78058e3a61bf6cbc36',
//     messagingSenderId: '691454814723',
//     projectId: 'fruits-app-5e4e0',
//     authDomain: 'fruits-app-5e4e0.firebaseapp.com',
//     storageBucket: 'fruits-app-5e4e0.appspot.com',
//     measurementId: 'G-X5GK5177LJ',
//   );
// }
